version: "3"
services:
    dotbak: &DEFAULTS
        image: "dotbak:dev"
        build:
            context: .
            dockerfile: docker/Dockerfile.dev
        hostname: dotbak
        stdin_open: true
        tty: true
        volumes:
            - '.:/src'
        working_dir: '/src'
    
    dotbak-py38:
        image: "dotbak:dev-py38"
        build:
            context: .
            dockerfile: docker/Dockerfile.dev-py38
        <<: *DEFAULTS
    
    dotbak-py39:
        image: "dotbak:dev-py38"
        build:
            context: .
            dockerfile: docker/Dockerfile.dev-py39
        <<: *DEFAULTS
    
    dotbak-py310:
        image: "dotbak:dev-py38"
        build:
            context: .
            dockerfile: docker/Dockerfile.dev-py310
        <<: *DEFAULTS
    
    dotbak-py311:
        image: "dotbak:dev-py38"
        build:
            context: .
            dockerfile: docker/Dockerfile.dev-py311
        <<: *DEFAULTS
