language: python
sudo: false
script: ./scripts/travis.sh
os:
  - linux
python:
  - 3.5
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.8
      dist: xenial
      sudo: true
services:
  - memcached
  - redis-server
